# -*- coding: utf-8 -*-
"""Stemming-and-Lemmatization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KtGT4f6nkBv1_6hILExR_88NIgTZ8fxF

### Stemming:
Reducing a word to its stem that affixes to suffixes and prefixes or to the roots of word
"""

sample = "I am shocked by how shockingly shocking you are"

import nltk
from nltk.stem import PorterStemmer, LancasterStemmer

porter = PorterStemmer()
lancaster = LancasterStemmer()

words_to_stem = ["shocked", "shocking", "shockingly", "happy", "happier", "happiest", "amazed", "amazing", "amazingly"]

stemmed_words = [(porter.stem(word), lancaster.stem(word)) for word in words_to_stem]
stemmed_words

"""### Lemmatization:
Text normalization technique used in Natural Language Processing (NLP), that switches any kind of a word to its base root mode. 

Lemmatization is responsible for grouping different inflected forms of words into the root form, having the same meaning.
"""

nltk.download("wordnet")
nltk.download('omw-1.4')

words = ["shock", "shocking", "shocked", "amazing", "amazed", "amaze"]

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

lemmatized_list = [lemmatizer.lemmatize(word) for word in words]
lemmatized_list

"""As you can see from above output, there is no change of words.

That is because lemmatization also requires parts of speech tag as shown below.
"""

from nltk.corpus import wordnet

new_lemmatized_list = [lemmatizer.lemmatize(word, wordnet.VERB) for word in words]
new_lemmatized_list

