# -*- coding: utf-8 -*-
"""Stopwords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yAaFUFZLI0atu4CR_KlgWsKgJXNYDoIj
"""

sample_tweet = """
Elon Musk
@elonmusk
Twitter is rolling out View Count, so you can see how many times a tweet has been seen! This is normal for video.

Shows how much more alive Twitter is than it may seem, as over 90% of Twitter users read, but don’t tweet, reply or like, as those are public actions."""

sample_tweet

import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

stop_words = stopwords.words("english")
stop_words[:15]

stop_words = set(stop_words)

sample_tweet.lower()

sample_tweet = sample_tweet.lower().split()

sample_tweet_no_stopwords = [word for word in sample_tweet if word not in stop_words]
final_tweet = (" ").join(sample_tweet_no_stopwords)
final_tweet

